apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe-backend
  template:
    metadata:
      labels:
        app: tic-tac-toe-backend
    spec:
      containers:
      - image: tic-tac-toe-backend
        name: tic-tac-toe-backend
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: tic-tac-toe