apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tic-tac-toe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /21
            pathType: Prefix
            backend:
              service:
                name: tic-tac-toe-backend
                port:
                  number: 80