apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-backend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: app.videomeet.online
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: tic-tac-toe-backend